version: '3'

vars:
  PROGRAM: bump
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'
  BIN_DIR: bin

  LINUX: '{{.BIN_DIR}}/{{.PROGRAM}}_linux_amd64'
  WINDOWS: '{{.BIN_DIR}}/{{.PROGRAM}}_windows_amd64.exe'
  VERSION:
    sh: 'git describe --tags $(git rev-list --tags --max-count=1)'

tasks:
  default:
    desc: Build the bump project
    cmds:
      - task: build

  build:
    desc: 'Build the bump project'
    deps: [vet]
    cmds:
      - task: build-linux
      - task: build-windows

  build-linux:
    desc: Build the Linux binary
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}}" -o {{.LINUX}}  ./cmd/{{.PROGRAM}}
    internal: true

  build-windows:
    desc: Build the Windows binary
    cmds:
      - GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}}" -o {{.WINDOWS}} ./cmd/{{.PROGRAM}}
    internal: true

  vet:
    desc: Vet the code
    deps: [fmt]
    cmds:
      - go vet ./...

  fmt:
    desc: Fmt the code
    cmds:
      - go fmt ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean the build artifacts
    cmds:
      - '{{.SHELL}} rm -r {{.BIN_DIR}}'
